.TH PYBABELFISH "1" "Mar 2008" "" ""
.SH NAME
pybabelfish \- convert Python objects into human-readable strings
.SH SYNOPSIS
.B pybabelfish
[options]
.SH DESCRIPTION
This script converts Python objects into human-readable strings for the
NWS web interface.
.TP
\fB\-h\fR \fI<host>\fR
hostname of the NWS server
.TP
\fB\-p\fR \fI\<port>\fR 
port number of the NWS server
.SH AUTHOR
Written by REvolution Computing, Inc.
.SH "REPORTING BUGS"
To report a bug, visit \fIhttp://sourceforge.net/projects/nws-py/\fR
.SH COPYRIGHT
Copyright \(co 2007-2008 REvolution Computing, Inc.
.SH "SEE ALSO"
pybabelfishd(1)
