.TH PYTHONNWSSLEIGHWORKER "1" "Mar 2008" "" ""
.SH NAME
PythonNWSSleighWorker \- Executes the Python NWS Sleigh Worker
.SH SYNOPSIS
.B PythonNWSSleighWorker
.SH DESCRIPTION
This script is executed on the worker machines, possibly via ssh,
to start the Python NWS sleigh workers.  It is executed when
constructing a Sleigh object, and is intended for internal use.
.SH AUTHOR
Written by REvolution Computing, Inc.
.SH "REPORTING BUGS"
To report a bug, visit \fIhttp://sourceforge.net/projects/nws-py/\fR
.SH COPYRIGHT
Copyright \(co 2007-2008 REvolution Computing, Inc.
